name: dbt CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: odap
          POSTGRES_PASSWORD: odap
          POSTGRES_DB: odap
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U odap -d odap"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres pandas sqlalchemy psycopg2-binary pyarrow

      # TẠO DBT PROFILE CHO CI
      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          order_to_delivery:
            target: ci
            outputs:
              ci:
                type: postgres
                host: localhost
                user: odap
                password: odap
                port: 5432
                dbname: odap
                schema: public
                threads: 4
          EOF

      - name: Install dbt packages
        working-directory: dbt
        run: dbt deps

      - name: Debug dbt connection
        working-directory: dbt
        run: dbt debug

      # DOWNLOAD FULL DATA (ĐÃ FIX THIẾU CUSTOMERS)
      - name: Download dataset
        run: |
          mkdir -p data/landing

          wget -O data/landing/olist_orders_dataset.csv https://raw.githubusercontent.com/olist/work-at-olist-data/master/datasets/olist_orders_dataset.csv
          wget -O data/landing/olist_order_items_dataset.csv https://raw.githubusercontent.com/olist/work-at-olist-data/master/datasets/olist_order_items_dataset.csv
          wget -O data/landing/olist_products_dataset.csv https://raw.githubusercontent.com/olist/work-at-olist-data/master/datasets/olist_products_dataset.csv
          wget -O data/landing/olist_sellers_dataset.csv https://raw.githubusercontent.com/olist/work-at-olist-data/master/datasets/olist_sellers_dataset.csv
          wget -O data/landing/olist_customers_dataset.csv https://raw.githubusercontent.com/olist/work-at-olist-data/master/datasets/olist_customers_dataset.csv

      # PIPELINE DATA
      - name: Copy landing data to Bronze
        run: python scripts/load_raw.py

      - name: Convert Bronze to Silver
        run: python scripts/bronze_to_silver.py

      - name: Load Silver data into Postgres raw
        run: python scripts/load_silver_to_dw.py

      # DBT
      - name: Run dbt models
        working-directory: dbt
        run: dbt run

      - name: Run dbt tests
        working-directory: dbt
        run: dbt test
